version: '3'
services:
  mariadb:
    image: mariadb:10.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_app
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
